#ifndef PHIPAC_H
#define PHIPAC_H

/*
 * phipac.h  header for the matrix multiplication functions
 *           generated by PHiPAC
 *
 * Written by Richard Rogers <rprogers@ee.washington.edu>
 *
 * Copyright (C) 2011 Jeff Bilmes
 * Licensed under the Open Software License version 3.0
 * See COPYING or http://opensource.org/licenses/OSL-3.0
 * 
 */

#ifdef __cplusplus
extern "C" {
#endif

void
mul_mfmf_mf(const int M, const int K, const int N, 
	    const float *const A, const float *const B, float *const C, 
	    const int Astride, const int Bstride, const int Cstride);

void
mul_mdmd_md(const int M, const int K, const int N, 
	    const double *const A, const double *const B, double *const C, 
	    const int Astride, const int Bstride, const int Cstride);

#ifdef __cplusplus
}
#endif

#endif
